server:
  port: 8080

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: foobared
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0

# 登录配置
login:
  username: admin
  password: 123
