server:
  port: 8080

spring:
  application:
    name: goods-management
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: foobared
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0

app:
  login:
    username: admin
    password: 123
